In [1]:
#Numpy - Array Manipulation 

In [2]:
import numpy as np

In [3]:
arr  = np.random.randint(1, 100, (3, 4))

In [7]:
arr

array([[15, 59, 20, 96],
       [49, 46, 46,  5],
       [49, 84, 71, 72]])

In [5]:
arr.reshape((6,2))

array([[15, 59],
       [20, 96],
       [49, 46],
       [46,  5],
       [49, 84],
       [71, 72]])

In [6]:
arr.T

array([[15, 49, 49],
       [59, 46, 84],
       [20, 46, 71],
       [96,  5, 72]])

In [8]:
arr.flatten()

array([15, 59, 20, 96, 49, 46, 46,  5, 49, 84, 71, 72])

In [21]:
a = np.linspace(1, 10, 8)
a

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [22]:
arr1 = np.array([1, 2, 3, 4])

In [27]:
print(np.expand_dims.__doc__)


    Expand the shape of an array.

    Insert a new axis that will appear at the `axis` position in the expanded
    array shape.

    Parameters
    ----------
    a : array_like
        Input array.
    axis : int or tuple of ints
        Position in the expanded axes where the new axis (or axes) is placed.

        .. deprecated:: 1.13.0
            Passing an axis where ``axis > a.ndim`` will be treated as
            ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
            be treated as ``axis == 0``. This behavior is deprecated.

    Returns
    -------
    result : ndarray
        View of `a` with the number of dimensions increased.

    See Also
    --------
    squeeze : The inverse operation, removing singleton dimensions
    reshape : Insert, remove, and combine dimensions, and resize existing ones
    atleast_1d, atleast_2d, atleast_3d

    Examples
    --------
    >>> import numpy as np
    >>> x = np.array([1, 2])
    >>> x.shape
    (2,)

    The followi

In [35]:
np.expand_dims(np.expand_dims(arr1, axis=1), axis=0)

array([[[1],
        [2],
        [3],
        [4]]])

In [12]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4]])

In [13]:
arr2 = np.array([[1], [2], [3]])

In [14]:
arr2

array([[1],
       [2],
       [3]])

In [15]:
arr2.squeeze()

array([1, 2, 3])

In [16]:
arr

array([[44, 43, 90, 77],
       [ 9, 76, 48, 55],
       [64, 79, 86, 57]])

In [17]:
arr.squeeze()

array([[44, 43, 90, 77],
       [ 9, 76, 48, 55],
       [64, 79, 86, 57]])

In [22]:
#squeeze ফাংশন শুধু তখনই কাজ করবে যখন টু ডাইমেনশন এরেতে প্রতিটা এরেতে একটা করে ভ্যালু থাকবে। 

In [37]:
arr1

array([1, 2, 3, 4])

In [38]:
np.repeat(arr1, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [72]:
np.roll(arr1, 2)

array([3, 4, 1, 2])

In [26]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
#numpy-Binary Operations

In [29]:
arr1 = np.random.randint(1, 10, (3, 3))

In [30]:
arr2 = np.random.randint(1, 10, (3, 3))

In [31]:
arr1

array([[4, 9, 6],
       [8, 5, 6],
       [3, 6, 3]])

In [32]:
arr2

array([[4, 7, 1],
       [1, 4, 9],
       [7, 5, 9]])

In [33]:
arr1+arr2

array([[ 8, 16,  7],
       [ 9,  9, 15],
       [10, 11, 12]])

In [34]:
arr1-arr2

array([[ 0,  2,  5],
       [ 7,  1, -3],
       [-4,  1, -6]])

In [35]:
arr1*arr2

array([[16, 63,  6],
       [ 8, 20, 54],
       [21, 30, 27]])

In [36]:
arr1%arr2

array([[0, 2, 0],
       [0, 1, 6],
       [3, 1, 3]])

In [37]:
arr1&arr2

array([[4, 1, 0],
       [0, 4, 0],
       [3, 4, 1]])

In [38]:
~arr1

array([[ -5, -10,  -7],
       [ -9,  -6,  -7],
       [ -4,  -7,  -4]])

In [39]:
arr1>arr2

array([[False,  True,  True],
       [ True,  True, False],
       [False,  True, False]])

In [41]:
arr1[arr1>arr2]

array([9, 6, 8, 5, 6])

In [42]:
#Numpy - String Functions

In [44]:
arr = np.array(["emdadul", "tareque"])

In [45]:
np.char.upper(arr)

array(['EMDADUL', 'TAREQUE'], dtype='<U7')

In [46]:
np.char.title(arr)

array(['Emdadul', 'Tareque'], dtype='<U7')

In [47]:
np.char.capitalize(arr)

array(['Emdadul', 'Tareque'], dtype='<U7')

In [48]:
#numpy - Mathematical Functions

In [49]:
arr1

array([[4, 9, 6],
       [8, 5, 6],
       [3, 6, 3]])

In [51]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849, -0.2794155 ],
       [ 0.98935825, -0.95892427, -0.2794155 ],
       [ 0.14112001, -0.2794155 ,  0.14112001]])

In [52]:
np.cos(arr1)

array([[-0.65364362, -0.91113026,  0.96017029],
       [-0.14550003,  0.28366219,  0.96017029],
       [-0.9899925 ,  0.96017029, -0.9899925 ]])

In [53]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566, -0.29100619],
       [-6.79971146, -3.38051501, -0.29100619],
       [-0.14254654, -0.29100619, -0.14254654]])

In [54]:
np.log10(arr1)

array([[0.60205999, 0.95424251, 0.77815125],
       [0.90308999, 0.69897   , 0.77815125],
       [0.47712125, 0.77815125, 0.47712125]])

In [55]:
np.sqrt(arr1)

array([[2.        , 3.        , 2.44948974],
       [2.82842712, 2.23606798, 2.44948974],
       [1.73205081, 2.44948974, 1.73205081]])

In [57]:
np.power(arr1, 2)

array([[16, 81, 36],
       [64, 25, 36],
       [ 9, 36,  9]])

In [58]:
np.mean(arr1)

5.555555555555555

In [73]:
np.median(arr1)

np.float64(2.5)