### What is numpy

NumPy is a Python library used for dealing with arrays. In Python, we use the list inplace of the array but it’s slow to process. NumPy array is a powerful N-dimensional array object and is used in linear algebra, Fourier transform, and random number capabilities. It provides an array object much faster than traditional Python lists.

In [60]:
import numpy as np

## Convert list to numpy array

In [61]:
l = [1,2,3,4]

In [62]:
np.array(l)

array([1, 2, 3, 4])

In [63]:
np.asarray(l)

array([1, 2, 3, 4])

In [64]:
np.asanyarray(l)

array([1, 2, 3, 4])

### Difference Between np.array() & np.asarray() 
The np.array() in Python is used to convert a list, tuple, etc. into a Numpy array.
The numpy.asarray()function is used when we want to convert the input to an array. Input can be lists, lists of tuples, tuples, tuples of tuples, tuples of lists and arrays.

In Python, NumPy array and NumPy asarray are used to convert the data into ndarray. If we talk about the major difference that is when we make a NumPy array using np.array, it creates a copy of the object array or the original array and does not reflect any changes made to the original array. Whereas on the other hand, when we try to use NumPy asarray, it would reflect all the changes made to the original array.

In [65]:
import numpy as np
 
# creating array
a = np.array([ 2, 3, 4, 5, 6])
print("Original array : ",a)
 
# assigning value to np.array
np_array = np.array(a)
a[3] = 0
print("np.array Array : ",np_array)
 
# assigning value to np.asarray
np_array = np.asarray(a)
a[3] = 0
print("np.asarray Array : ",np_array)


Original array :  [2 3 4 5 6]
np.array Array :  [2 3 4 5 6]
np.asarray Array :  [2 3 4 0 6]


In [66]:
l = [1,2,3,4]
array = np.array(l)
print("Original Array: ", array)

num_array = np.array(array)
array[3] = 10
print("np.array: ", num_array)

num_array = np.asarray(array)
array[3] = 10
print("np.asarray: ", num_array)


Original Array:  [1 2 3 4]
np.array:  [1 2 3 4]
np.asarray:  [ 1  2  3 10]


In [67]:
l = [1,2,3,4]
array = np.asarray(l)
print("Original Array: ", array)
print("Original array address: ", id(array))

num_array = np.array(array)
array[3] = 10
print("np.array: ", num_array)
print("np.arrayarray address: ", id(num_array))

num_array = np.asarray(array)
array[3] = 10
print("np.asarray: ", num_array)
print("np.asarray array address: ", id(num_array))

Original Array:  [1 2 3 4]
Original array address:  4436121360
np.array:  [1 2 3 4]
np.arrayarray address:  4436120208
np.asarray:  [ 1  2  3 10]
np.asarray array address:  4436121360



1. np.array is the most common function for converting input data to a NumPy array. It copies the input data by default.
2. np.asarray is more memory efficient than np.array because it does not copy the input data if it is already a NumPy array.
3. np.asanyarray converts input data to a NumPy array, even if the input data is a subclass of ndarray. if input data is a matrix. np.asanyarray did not convert matrix to array. because matrix is subset of array. 


In [68]:
l = [1,2,3,4]

In [69]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [70]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [71]:
l = [[1,2,3,4], [5, 6, 7, 8]]

In [72]:
np.asanyarray(l)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
mtx = np.matrix(l)

In [74]:
mtx

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [75]:
np.asanyarray(mtx)

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [76]:
np.asarray(mtx)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.array(mtx)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Genarate array using fromfunction

np.fromfunction is a array genarative function 

In [78]:
np.fromfunction(lambda i, j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [79]:
np.fromfunction(lambda x, y: x == y, (4,2))

array([[ True, False],
       [False,  True],
       [False, False],
       [False, False]])

In [80]:
np.fromfunction(lambda i, j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [81]:
np.fromiter((i for i in range(3)), int)

array([0, 1, 2])

In [82]:
iterable = (i*i for i in range(5))

In [83]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [84]:
np.fromstring("1 23 456 7890", sep=' ', dtype=np.int64)

array([   1,   23,  456, 7890])

In [85]:
np.fromstring('123 456', sep = ' ')

array([123., 456.])

In [86]:
np.fromstring('123,456', sep = ',')

array([123., 456.])

### 

## numpy methods

In [87]:
arr = np.fromiter(range(5), np.int32)
arr

array([0, 1, 2, 3, 4], dtype=int32)

In [88]:
arr.size

5

In [89]:
arr = np.fromfunction(lambda i, j: i + j, (5, 3))
arr

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [90]:
arr.size

15

In [91]:
len(arr)

5

In [92]:
arr.ndim

2

In [93]:
arr.shape

(5, 3)

In [94]:
arr = np.array([1, 2, 3, 4])

In [95]:
arr.ndim

1

In [96]:
arr.size

4

In [97]:
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [98]:
arr2.ndim

2

In [99]:
arr2.size

8

In [100]:
arr.shape

(4,)

In [101]:
arr2.shape

(2, 4)

In [102]:
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],["MD", "Emdadul", "Hoque", "Tareque"]])

In [103]:
arr3.ndim

2

In [104]:
arr3.shape

(3, 4)

In [105]:
arr.dtype

dtype('int64')

In [106]:
arr3.dtype

dtype('<U21')

In [107]:
np.arange(1.2, 5.3) # নরমাল range এবং arange এর মধ্যে পার্থক্য হচ্ছে numpy এর রেঞ্জ ফাংশন ফ্লোটিং ডেটা প্রডিউজ করতে পারে। 

array([1.2, 2.2, 3.2, 4.2, 5.2])

In [108]:
np.arange(1.2, 5.3, 0.5)

array([1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7, 5.2])

In [109]:
arr = np.linspace(2, 10, 5)

In [110]:
arr

array([ 2.,  4.,  6.,  8., 10.])

In [111]:
arr[0]

np.float64(2.0)

In [112]:
type(arr[0])

numpy.float64

In [113]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [114]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [115]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
arr = np.random.randn(3, 4) 

In [118]:
import pandas as pd

In [119]:
pd.DataFrame(arr)

0         1         2         3
0  0.308095  0.304697 -1.268205  1.257858
1 -0.676742  0.668078 -2.969830  0.785611
2  1.971394 -0.219798 -0.619688 -0.926644

In [120]:
np.random.rand(3, 4)

array([[0.95864533, 0.41801057, 0.44616043, 0.18213986],
       [0.05000103, 0.80796294, 0.49855484, 0.49778559],
       [0.13733114, 0.24651926, 0.36374829, 0.94554061]])

In [121]:
np.random.randint(1, 10, (3, 4))

array([[6, 7, 1, 1],
       [1, 7, 7, 6],
       [8, 2, 6, 5]])

In [127]:
arr = np.random.randint(1, 10, (10, 20))

In [128]:
pd.DataFrame(arr)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   3   4   4   1   6   3   7   3   3   2   9   5   7   7   8   9   5   3   3   
1   3   1   5   4   8   5   7   2   8   6   3   2   2   2   7   2   3   4   6   
2   6   9   7   2   2   6   4   5   5   3   5   8   7   4   7   8   5   3   8   
3   1   1   8   4   1   5   1   2   8   9   4   9   6   2   5   5   6   1   8   
4   8   8   6   9   5   6   9   4   7   3   8   6   6   1   1   7   1   5   2   
5   9   4   7   9   7   7   6   3   8   6   7   7   3   4   8   6   9   5   4   
6   2   8   2   4   7   6   4   2   8   5   1   3   5   3   4   5   6   7   2   
7   3   2   1   8   2   5   6   8   1   1   3   5   1   5   3   2   9   3   1   
8   1   9   6   4   7   1   5   7   6   3   4   3   3   9   8   7   6   1   7   
9   4   1   9   4   9   1   7   4   3   8   6   8   2   7   7   6   5   1   8   

   19  
0   8  
1   9  
2   8  
3   3  
4   5  
5   9  
6   3  
7   8  
8   2  
9   4

In [129]:
df = pd.DataFrame(arr)

In [130]:
df.to_csv('sample_data.csv')

In [145]:
arr = np.random.randint(1, 5, 27)
arr

array([2, 2, 4, 1, 1, 1, 3, 3, 4, 2, 2, 3, 3, 1, 4, 1, 4, 2, 2, 4, 4, 4,
       4, 3, 3, 4, 2])

In [146]:
arr.reshape((3, 3, 3))

array([[[2, 2, 4],
        [1, 1, 1],
        [3, 3, 4]],

       [[2, 2, 3],
        [3, 1, 4],
        [1, 4, 2]],

       [[2, 4, 4],
        [4, 4, 3],
        [3, 4, 2]]])

In [148]:
arr = np.random.randint(1, 10, (3, 4))

In [149]:
arr.reshape(6,2) # this function using in image processing 

array([[8, 9],
       [5, 1],
       [2, 1],
       [4, 8],
       [6, 3],
       [6, 7]])

In [172]:
arr = np.random.randint(1, 10, (3, 4))

In [173]:
arr

array([[6, 9, 1, 3],
       [6, 2, 3, 2],
       [2, 1, 3, 8]])

In [183]:
arr[1:, 2:]

array([[3, 2],
       [3, 8]])

In [152]:
arr[0][0]

np.int64(4)

In [109]:
arr[0][1]

9

In [110]:
arr[1][2]

6

In [111]:
arr[1][3]

9

In [112]:
arr[0:3]

array([[4, 9, 8, 7],
       [4, 9, 6, 9],
       [8, 4, 1, 3]])

In [113]:
arr[0:3][0][2]

8

In [114]:
arr[0:3, [0, 2]]

array([[4, 8],
       [4, 6],
       [8, 1]])

In [165]:
arr = np.random.randint(1, 100, (5,5))

In [166]:
arr

array([[80, 18, 87, 12, 43],
       [22, 60, 30, 70,  5],
       [16, 19, 74, 55, 45],
       [70, 88, 28, 17, 54],
       [50,  4, 51, 18, 34]])

In [167]:
arr>50

array([[ True, False,  True, False, False],
       [False,  True, False,  True, False],
       [False, False,  True,  True, False],
       [ True,  True, False, False,  True],
       [False, False,  True, False, False]])

In [168]:
arr[arr>50]

array([80, 87, 60, 70, 74, 55, 70, 88, 54, 51])

In [169]:
arr

array([[80, 18, 87, 12, 43],
       [22, 60, 30, 70,  5],
       [16, 19, 74, 55, 45],
       [70, 88, 28, 17, 54],
       [50,  4, 51, 18, 34]])

In [170]:
arr[1:3, [1, 2]]

array([[60, 30],
       [19, 74]])

In [185]:
arr1 = np.random.randint(1, 5, (3,3))

In [186]:
arr2 = np.random.randint(1, 5, (3,3))

In [187]:
arr1

array([[4, 2, 4],
       [2, 2, 4],
       [1, 1, 1]])

In [188]:
arr2

array([[2, 4, 2],
       [4, 3, 2],
       [3, 2, 4]])

In [189]:
arr1+arr2

array([[6, 6, 6],
       [6, 5, 6],
       [4, 3, 5]])

In [190]:
arr1-arr2

array([[ 2, -2,  2],
       [-2, -1,  2],
       [-2, -1, -3]])

In [191]:
arr1 * arr2

array([[8, 8, 8],
       [8, 6, 8],
       [3, 2, 4]])

In [192]:
arr1@arr2 #matrix multiplication

array([[28, 30, 28],
       [24, 22, 24],
       [ 9,  9,  8]])