In [1]:
#sort, search, Counting Functions

In [2]:
import numpy as np

In [3]:
arr = np.array([4, 1, 2, 3, 1, 9, 4, 5, 6])

In [4]:
np.sort(arr)

array([1, 1, 2, 3, 4, 4, 5, 6, 9])

In [6]:
print(np.searchsorted.__doc__)


    Find indices where elements should be inserted to maintain order.

    Find the indices into a sorted array `a` such that, if the
    corresponding elements in `v` were inserted before the indices, the
    order of `a` would be preserved.

    Assuming that `a` is sorted:

    ======  ============================
    `side`  returned index `i` satisfies
    ======  ============================
    left    ``a[i-1] < v <= a[i]``
    right   ``a[i-1] <= v < a[i]``
    ======  ============================

    Parameters
    ----------
    a : 1-D array_like
        Input array. If `sorter` is None, then it must be sorted in
        ascending order, otherwise `sorter` must be an array of indices
        that sort it.
    v : array_like
        Values to insert into `a`.
    side : {'left', 'right'}, optional
        If 'left', the index of the first suitable location found is given.
        If 'right', return the last such index.  If there is no suitable
        index, return either 

In [7]:
np.searchsorted(arr, 34)

np.int64(9)

In [8]:
arr1 = np.array([0, 2, 123, 12453, 123, 0, 9, 0, 0, 0])

In [9]:
np.count_nonzero(arr1)

np.int64(5)

In [10]:
arr

array([4, 1, 2, 3, 1, 9, 4, 5, 6])

In [14]:
arr[np.where(arr >= 6)]

array([9, 6])

In [11]:
np.where(arr > 3)

(array([0, 5, 6, 7, 8]),)

In [14]:
np.extract(arr > 3, arr)

array([4, 9, 4, 5, 6])

In [15]:
#Numpy - Byte Swapping

In [16]:
arr.byteswap()

array([288230376151711744,  72057594037927936, 144115188075855872,
       216172782113783808,  72057594037927936, 648518346341351424,
       288230376151711744, 360287970189639680, 432345564227567616])

In [17]:
#Numpy - Copies & Views

In [18]:
a = np.copy(arr)

In [19]:
a

array([4, 1, 2, 3, 1, 9, 4, 5, 6])

In [20]:
id(a)

140539568719216

In [21]:
id(arr)

140539572743952

In [22]:
b = arr.view()

In [23]:
b

array([4, 1, 2, 3, 1, 9, 4, 5, 6])

In [24]:
b[0] = 67

In [25]:
b

array([67,  1,  2,  3,  1,  9,  4,  5,  6])

In [26]:
arr

array([67,  1,  2,  3,  1,  9,  4,  5,  6])

In [27]:
id(b)

140539572744624

In [28]:
id(arr)

140539572743952

In [29]:
#Numpy - Matrix Library

In [30]:
import numpy.matlib as nm

In [31]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [32]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
#numpy - linear algebra

In [39]:
arr1 = np.random.randint([[2,3], [4, 5]])

In [40]:
arr1

array([[0, 2],
       [1, 3]])

In [41]:
arr2 = np.random.randint([[5,3], [2, 5]])

In [42]:
arr2

array([[2, 2],
       [1, 2]])

In [43]:
np.dot(arr1, arr2)

array([[2, 4],
       [5, 8]])

In [44]:
arr1@arr2

array([[2, 4],
       [5, 8]])